# We could use `@actions-rs/cargo` Action ability to automatically install `cross` tool
# in order to compile our application for some unusual targets.

on: [push, pull_request]

name: Cross-compile

jobs:
  build:
    name: Build
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
            suffix: ''
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            suffix: ''
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            suffix: .exe
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies Ubuntu
        run: export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig
        if: matrix.os == 'ubuntu-latest'
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: tool-new-release-${{ matrix.target }}
          path: ./target/${{ matrix.target }}/release/tool-new-release${{ matrix.suffix }}
